name: tfsms_app_frontend
description: Your app description

publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.3.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  provider: ^6.1.1
  socket_io_client: ^3.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
