export interface GratisIssue {
  id?: number; // Optional: ID is generated by the backend for new entries
  issueDate: string; // YYYY-MM-DD format (from HTML date input, or ISO string from backend)
  purpose: string;
  receiver: string;
  quantityKg: number;
  teaGrade: string;
  batchLotNumber?: string; // Optional
  referenceMemo?: string; // Optional
   remarks?: string; // Optional
  createdAt?: string; // Optional: Auto-generated by backend, typically ISO string
  updatedAt?: string; // Optional: Auto-generated by backend, typically ISO string
}