// src/app/models/green-leaf-collection.interface.ts
export interface GreenLeafCollection {
  collectionId?: number; // Optional for creation, auto-generated by backend
  collectionDate: string; // ISO string (YYYY-MM-DD)
  supplierId: number;
  initialNormalTeaLeafWeight: number;
  initialGoldenTipTeaLeafWeight: number;
  normalTeaLeafWeight: number; // The final, potentially edited weight
  goldenTipTeaLeafWeight: number; // The final, potentially edited weight
  hasDifference: boolean;
}
