// export interface PackedTea {
//   packedTeaId?: number; // Primary key, optional for creation (generated by backend)
//   grade: string | null; // FIX: Made nullable to match component's initialization
//   gardenMark: string;
//   financialYear: number;
//   packingType: string | null; // FIX: Made nullable to match component's initialization
//   initialWeightKg: number;
//   packingDate: string; // YYYY-MM-DD format
//   createdAt?: string;
//   updatedAt?: string;
  
//   // Include StockLedgerEntry for display purposes if needed (e.g., in a table)
//   stockLedgerEntry?: {
//     stockLedgerEntryId: number;
//     status: string;
//     currentWeightKg: number;
//     invoiceId?: number;
//   };
// }

// export interface PackedTea {
//   packedTeaId?: number; // Primary key, optional for creation (generated by backend)
//   grade: string; // Remove null, make it required when sending to backend
//   gardenMark: string;
//   financialYear: number;
//   packingType: string; // Remove null, make it required when sending to backend
//   initialWeightKg: number;
//   packingDate: string; // YYYY-MM-DD format
//   createdAt?: string;
//   updatedAt?: string;
  
//   // Include StockLedgerEntry for display purposes
//   stockLedgerEntry?: {
//     stockLedgerEntryId: number;
//     status: string;
//     currentWeightKg: number;
//     invoiceId?: number;
//   };
// }

export interface PackedTea {
  packedTeaId?: number; // Primary key, optional for creation (generated by backend)
  grade: string | null; // Allow null to match backend
  gardenMark: string;
  financialYear: number;
  packingType: string | null; // Allow null to match backend
  initialWeightKg: number;
  packingDate: string; // YYYY-MM-DD format
  createdAt?: string;
  updatedAt?: string;
  
  // Include StockLedgerEntry for display purposes
  stockLedgerEntry?: {
    stockLedgerEntryId: number;
    status: string;
    currentWeightKg: number;
    invoiceId?: number;
  };
}