export interface SalesCharge {
  id?: number; // Optional: ID is generated by the backend for new entries
  saleReference: string; // e.g., InvoiceNumber or Sales Order ID
  chargeType: string; // e.g., "Commission", "Packaging Fee", "Delivery Charge"
  amount: number; // Monetary amount of the charge
  chargeDate: string; // YYYY-MM-DD format (from HTML date input, or ISO string from backend)
  description?: string; // Optional detailed description
  createdAt?: string; // Optional: Auto-generated by backend, typically ISO string
  updatedAt?: string; // Optional: Auto-generated by backend, typically ISO string
}