export interface SalesEntry {
  id?: number; // Optional: ID is generated by the backend for new entries
  invoiceNumber: string;
  saleDate: string; // YYYY-MM-DD format (from HTML date input, or ISO string from backend)
  customerName: string;
  teaGrade: string;
  quantityKg: number;
  unitPriceKg: number;
  totalAmount: number;
  remarks?: string; // Optional
  createdAt?: string; // Optional: Auto-generated by backend, typically ISO string
  updatedAt?: string; // Optional: Auto-generated by backend, typically ISO string
}
