// src/app/models/sales-charge.interface.ts

/**
 * @interface SalesCharge
 * @description Defines the structure for a single Sales Charge record
 */
export interface SalesCharge {
  salesChargeId?: number; // Optional for creation
  invoiceId?: number; // Will be set when creating
  // REMOVED: saleReference - this column doesn't exist in database
  chargeType: string; // Required: e.g., "Commission", "Packaging Fee"
  amount: number; // Required: monetary amount
  chargeDate?: string | null; // Optional: defaults to invoice date
  description?: string | null; // Optional: detailed description
  createdAt?: string | null; // Auto-generated by backend
  updatedAt?: string | null; // Auto-generated by backend
}