// src/app/models/sales-entry.interface.ts

/**
 * @interface SalesEntry
 * @description Defines the structure for a single Sales Entry record in the frontend.
 * This mirrors the SalesEntry model from your .NET backend.
 */
export interface SalesEntry { // FIX: Ensure 'export' keyword is present
  id?: number; // Optional: ID is generated by the backend for new entries
  invoiceId?: number | null; // FIX: Make nullable, as it can be null from backend
  invoiceNumber: string;
  saleDate: string; // YYYY-MM-DD format (from HTML date input, or ISO string from backend)
  customerName: string;
  teaGrade: string;
  quantityKg: number;
  unitPriceKg: number;
  totalAmount: number;
  // DEFINITIVE FIX: Removed remarks property
  createdAt?: string | null;
  updatedAt?: string | null;

  invoice?: {
    invoiceId: number;
    invoiceNumber: string;
    invoiceDate: string;
    brokerName: string;
    status: string;
  } | null; // FIX: Can be null
}
