class AppStrings {
  // English Strings
  static const Map<String, String> english = {
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    
    // Welcome Pages  
    'getReady': 'Get ready for',
    'newJourney': 'New Journey',
    'selectLanguage': 'Select Language',
    'termsOfService': 'Terms of Service',
    'termsConditions': 'Registered collectors affiliated with the factory, dealers accredited by the Sri Lanka Tea Board, and recognized tea growers are eligible to register as suppliers.\n\nTo qualify, they must demonstrate the capacity to meet the predefined specifications and quality standards set forth by the respective factory and the Sri Lanka Tea Board.',
    'acceptContinue': 'Accept & Continue',
    'youAreA': 'You are a',
    'grower': 'Grower',
    'collector': 'Collector',
    'next': 'Next',
    'pleaseSelectRole': 'Please select your role',
    'harvestDetailsReceived': 'Got your harvest\ndetails.',
    'continue': 'Continue',
    'settings': 'Settings',
    'darkMode': 'Dark Mode',
    'language': 'Language',
    'close': 'Close',
    'asACollector':'As A Collector',
    'letsStart': 'Let\'s Start',
    'asAGrower':'As a Grower',
    
    // Common UI Elements
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot Password?',
    'createAccount': 'Create Account',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccount': "Don't have an account?",
    'login': 'Login',
    'logout': 'Logout',
    
    // Navigation
    'home_page_title': 'Home Page\nGrower',
    'home': 'Home',
    'harvest': 'Harvest',
    'payments': 'Payments',
    'profile': 'Profile',
    'helpCenter': 'Help Center',
    'notifications': 'Notifications',
    'contactUs': 'Contact Us',
    
    // Help Center
    'fertilizer': 'Fertilizer',
    'loans': 'Loans',
    'insurance': 'Insurance',
    'weatherForecast': 'Weather Forecast',
    'marketPrices': 'Market Prices',
    
    // Form Fields
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'fullName': 'Full Name',
    'phoneNumber': 'Phone Number',
    'address': 'Address',
    'city': 'City',
    'postalCode': 'Postal Code',
    'bankName': 'Bank Name',
    'branchName': 'Branch Name',
    'accountNumber': 'Account Number',
    'accountHolder': 'Account Holder Name',
    
    // Messages
    'pleaseEnterEmail': 'Please enter your email',
    'pleaseEnterValidEmail': 'Please enter a valid email',
    'pleaseEnterPassword': 'Please enter your password',
    'passwordTooShort': 'Password must be at least 6 characters',
    'passwordsDontMatch': 'Passwords do not match',
    'registrationSuccessful': 'Registration Successful',
    'loginSuccessful': 'Login Successful',
    'loginFailed': 'Login Failed',
    'networkError': 'Network Error',
    'somethingWentWrong': 'Something went wrong',
    'thankYou': 'Thank You',
    'orderSubmittedSuccessfully': 'Order submitted successfully',
    'goHome': 'Go Home',
    
    // Grower Order Page
    'growerOrderPageTitle': 'Grower Order Page',
    'orderDetails': 'Order Details',
    'growerName': 'Grower Name',
    'teaVariety': 'Tea Variety',
    'selectTeaVariety': 'Select Tea Variety',
    'quantity': 'Quantity',
    'quantityInKg': 'Quantity (in kg)',
    'expectedDate': 'Expected Date',
    'dateYouCanGiveHarvest': 'Date you can give harvest',
    'additionalNotes': 'Additional Notes',
    'submitOrder': 'Submit Order',
    'pleaseSelectTeaVariety': 'Please select tea variety',
    'pleaseEnterQuantity': 'Please enter quantity',
    'pleaseEnterValidQuantity': 'Please enter valid quantity',
    'pleaseSelectDate': 'Please select date',
    'blackTea': 'Black Tea',
    'greenTea': 'Green Tea',
    'whiteTea': 'White Tea',
    'oolongTea': 'Oolong Tea',
    
    // Feedback Page
    'feedbackPageTitle': 'Feedback',
    'feedback': 'Feedback',
    'rateYourExperience': 'Rate Your Experience',
    'whatDescribesYourExperience': 'What Describes Your Experience',
    'additionalComments': 'Additional Comments',
    'tellUsMoreAboutYourExperience': 'Tell us more about your experience',
    'goodQuality': 'Good Quality',
    'onTime': 'On Time',
    'greatCommunication': 'Great Communication',
    'delay': 'Delay',
    'poorPackaging': 'Poor Packaging',
    'unresponsive': 'Unresponsive',
    'selected': 'Selected',
    'yourFeedback': 'Your Feedback',
    'pleaseTellUs': 'Please tell us about your experience',
    'rating': 'Rating',
    'tags': 'Tags',
    'tapToAddTags': 'Tap to add tags',
    'submitFeedback': 'Submit Feedback',
    'pleaseEnterFeedback': 'Please enter your feedback',
    'pleaseFillAtLeastOneField': 'Please fill at least one field',
    'pleaseSelectRating': 'Please select rating',
    'feedbackSubmittedSuccessfully': 'Feedback submitted successfully',
    'failedToSaveFeedback': 'Failed to save feedback',
    'databaseError': 'Database error',
    'service': 'Service',
    'quality': 'Quality',
    'price': 'Price',
    'delivery': 'Delivery',
    'support': 'Support',

    //collector 

  "pleaseConfirmPassword": "Please confirm your password",
  "passwordMismatch": "Passwords do not match",
  "signup": "Sign Up",
  "harvestRequests": "Harvest Requests",
   "paymentDetails": "Payment Details",
  "refNumber": "Ref Number",
  "amount": "Amount",
  "status": "Payment Status",
  "paymentDate": "Payment Date",
  "nic": "NIC",
  "name": "Name",
  "phone": "Phone",
  "notPaid": "Not Paid",
  "markAsPaid": "Mark as Paid",
  "paymentMarkedPaid": "Payment marked as Paid",
   "paymentHistory": "Payment History",
  "noPaymentHistory": "No payment history found.",
  "date": "Date",
  "collectorPayments": "Collector\nPayments",
  "toPay": "To Pay",
  "totalToPay": "Total To Pay",
  "ref": "Ref",
  "personalDetails": "Personal Details",
  "edit": "Edit",
  "save": "Save",
  "gender": "Gender",
  "dob": "Birthday date",
  "vehicleNumber": "Vehicle Number",

  //collector login
  "signingUp": "Signing up...",
  "signupSuccess": "Signup successful!",
  "signupFailed": "Signup failed:",
  "unknownError": "Unknown error",
  "connectionError": "Error connecting to server:",
  "fixErrors": "Please fix the errors in the form",
  "emailLabel": "Email",
  "enterEmail": "Please enter your email",
  "invalidEmail": "Please enter a valid email address",
  "passwordLabel": "Password",
  "enterPassword": "Please enter your password",
  "shortPassword": "Password must be at least 6 characters",
  "confirmPasswordLabel": "Confirm Password",
  "confirmPasswordRequired": "Please confirm your password",
  "signUpButton": "Sign up",
  "signInToggle": "Sign In",
  "signUpToggle": "Sign Up",

  //contact us

  "contactUsTitle": "Contact Us",
  "contactIntro": "We're here to assist you with any inquiries or concerns. Reach out to us for support, feedback, or general questions about our operations.",
  "contactMethodsTitle": "You can contact us by,",
  "call": "Call",
  "whatsapp": "Whatsapp",
  "navHome": "Home",
  "navNotification": "Notification",
  "navProfile": "Profile",
  "navContactUs": "Contact us",

  //fertilizer

  "fertilizerTitle": "Fertilizer Information",
  "totalFertilizer": "Total Fertilizer",

  //grower

  "harvestSummaryTitle": "Harvest Summary",
  "totalHarvest": "Total Harvest",
  "superTea": "Super Tea",
  "normalTea": "Normal Tea",
  "teaQualityDistribution": "Tea Quality Distribution",
  "growerHomeTitle": "Home Page\nGrower",
  "navHelp": "Help Center",
  "growerPaymentsTitle": "Grower Payments",
  "totalPayment": "Total Payment",
  "paymentTime": "Payment Time",
  "paymentMethod": "Payment Method",
  "noPayments": "No payment data found.",
  "helpCenterTitle": "Help Center",
  "nicNumber": "NIC Number",
  "birthday": "Birthday",
  "updateSuccess": "Details updated successfully!",
  "updateFailed": "Update failed.",
  "signInSuccess": "You have been signed in successfully.",
  "bankDetails": "Bank Details",
  "branch": "Branch",
  "holderName": "Holder Name",
  "submit": "Submit",
  "bankSuccess": "Bank details saved successfully!",
  "bankFail": "Failed to save bank details",
  "fillFields": "Please fill all required fields",
  "fieldRequired": "This field is required",
  "nicHint": "Enter NIC number",
  "addressLine1": "Address line 1",
  "addressLine2": "Address line 2 (Optional)",
  "selectGender": "Select Gender",
  "selectMethod": "Select method",
  "create": "Create Account",
  "required": "Required",
  "invalidPhone": "Invalid phone number",
  "dobRequired": "Please select date of birth",
  "genderRequired": "Please select gender",
  "paymentRequired": "Please select payment method",
  "signInFail": "Failed to sign in",
  "passwordLength": "Password must be at least 6 characters",
  "confirmPasswordHint": "Please confirm your password",
  "formError": "Please fix the errors in the form",
  "requestOrderDescription": "Request a Collector get picked up by\na nearby community",
  "requestOrder": "Request Order",
  "notification": "Notification",
  "quantityKg": "How many (kg):",
  "superLeafKg": "Super leaf (kg)",
  "greenLeafKg": "Green leaf (kg)",
  "harvestDate": "Date you can give harvest:",
  "transportMethod": "How to transport:",
  "saveOrder": "Save Order",
  "completeAllFields": "Please complete all fields",
  "orderSaved": "Order saved successfully!",
  "orderFailed": "Failed to save order",
  "selectDate": "Select date",
  "orders": "Orders",

  //notification

  "today": "Today",
  "earlier": "Earlier",
  "contact": "Contact",

  //grower account

  "editGrower": "Edit Grower",
  "enterFirstName": "Enter first name",
  "enterLastName": "Enter last name",
  "saveChanges": "Save Changes",

  //other
 
  "orderSuccessMessage": "You have been signed in successfully!",
  "harvestTitle": "Harvest",
  "navigateAddHarvest": "Navigate to Add Harvest screen",
  "settingsNotImplemented": "Settings not implemented yet",
  "monthly": "Monthly",
  "annually": "Annually",
  "monthlyOverview": "Monthly Overview",
  "annuallyOverview": "Annually Overview",
  "yourWeight": "Your Weight",
  "noDataAvailable": "No data available",
  "motivationalMessage": "You are doing great!",
  "placeholderDots": "...",
  "navNotifications": "Notification",
  "bankTransfer": "Bank Transfer",
  "fabNotImplemented": "FAB action not implemented",
  "growerOrderTitle": "New Order",
  "howManyKg": "How many (kg):",
  "superLeafHint": "Super leaf (kg)",
  "enterSuperLeaf": "Enter super leaf kg",
  "greenLeafHint": "Green leaf (kg)",
  "enterGreenLeaf": "Enter green leaf kg",
  "dateYouCanGive": "Date you can give harvest:",
  "pleasePickDate": "Please pick a date",
  "howToTransport": "How to transport:",
  "pleaseSelectTransport": "Please select transport method",
  "completeFields": "Please complete all fields",
  "orderSaveFailed": "Failed to save order",
  "navOrders": "Orders"

  };

  // Sinhala Strings
  static const Map<String, String> sinhala = {
    // Common
    'loading': 'පූරණය වෙමින්...',
    'error': 'වරදක්',
    'success': 'සාර්ථකයි',
    
    // Welcome Pages  
    'getReady': 'සූදානම් වන්න',
    'newJourney': 'නව ගමන',
    'selectLanguage': 'භාෂාව තෝරන්න',
    'termsOfService': 'සේවා කොන්දේසි',
    'termsConditions': 'කාර්ක්ෂානය සමඟ අනුබද්ධ ලියාපදිංචි එකතුකරුවන්, ශ්‍රී ලංකා තේ මණ්ඩලය විසින් ප්‍රතීතනය කරන ලද වෙළඳුන් සහ පිළිගත් තේ වගාකරුවන්ට සැපයුම්කරුවන් ලෙස ලියාපদිංচි වීමට සුදුසුකම් ඇත.\n\nඅදාළ කර්ම ශාලාව සහ ශ්‍රී ලංකා තේ මණ්ඩලය විසින් පම්වර කළ පූර්ව නිර්ණයන් කළ පිරිමිතීන් සහ ගුණ ත්මක ප්‍රමිතීන් සපුරාලීමේ ධාරිත්වයක් පෙන්විය යුතුය.',
    'acceptContinue': 'පිළිගෙන ඉදිරියට',
    'youAreA': 'ඔබ',
    'grower': 'ගොවියා',
    'collector': 'එකතු කරන්නා',
    'next': 'ඊළඟ',
    'pleaseSelectRole': 'කරුණාකර ඔබගේ භූමිකාව තෝරන්න',
    'harvestDetailsReceived': 'ඔබගේ අස්වනු\nතොරතුරු ලැබුණි.',
    'continue': 'ඉදිරියට',
    'settings': 'සැකසුම්',
    'darkMode': 'අඳුරු මාදිලිය',
    'language': 'භාෂාව',
    'close': 'වසන්න',
    'asACollector':'එක් රැස්කරන්නෙක් ලෙස',
    'letsStart': 'අපි ආරම්භ කරමු',
    'asAGrower':'ගොවියා ලෙස',
    
    // Common UI Elements
    'signIn': 'පිවිසෙන්න',
    'signUp': 'ලියාපදිංචි වෙන්න',
    'email': 'ඊමේල්',
    'password': 'මුරපදය',
    'confirmPassword': 'මුරපදය තහවුරු කරන්න',
    'forgotPassword': 'මුරපදය අමතකද?',
    'createAccount': 'ගිණුමක් සාදන්න',
    'alreadyHaveAccount': 'දැනටමත් ගිණුමක් තිබේද?',
    'dontHaveAccount': 'ගිණුමක් නැද්ද?',
    'login': 'පිවිසීම',
    'logout': 'ඉවත්වීම',
    
    // Navigation
    'home_page_title': 'මුල් පිටුව',
    'home': 'මුල් පිටුව',
    'harvest': 'අස්වැන්න',
    'payments': 'ගෙවීම්',
    'profile': 'පැතිකඩ',
    'helpCenter': 'උදව් මධ්‍යස්ථානය',
    'notifications': 'දැනුම්දීම්',
    'contactUs': 'අප හා සම්බන්ධ වන්න',
    
    // Help Center
    'fertilizer': 'පොහොර',
    'loans': 'ණය',
    'insurance': 'රක්ෂණය',
    'weatherForecast': 'කාලගුණ අනාවැකිය',
    'marketPrices': 'වෙළඳපොළ මිල',
    
    // Form Fields
    'firstName': 'මුල් නම',
    'lastName': 'අවසාන නම',
    'fullName': 'සම්පූර්ණ නම',
    'phoneNumber': 'දුරකථන අංකය',
    'address': 'ලිපිනය',
    'city': 'නගරය',
    'postalCode': 'තැපැල් කේතය',
    'bankName': 'බැංකුවේ නම',
    'branchName': 'ශාඛාවේ නම',
    'accountNumber': 'ගිණුම් අංකය',
    'accountHolder': 'ගිණුම්කරුගේ නම',
    
    // Messages
    'pleaseEnterEmail': 'කරුණාකර ඔබේ ඊමේල් ඇතුළත් කරන්න',
    'pleaseEnterValidEmail': 'කරුණාකර වලංගු ඊමේල් ඇතුළත් කරන්න',
    'pleaseEnterPassword': 'කරුණාකර ඔබේ මුරපදය ඇතුළත් කරන්න',
    'passwordTooShort': 'මුරපදය අවම වශයෙන් අක්ෂර 6 ක් විය යුතුය',
    'passwordsDontMatch': 'මුරපද නොගැළපේ',
    'registrationSuccessful': 'ලියාපදිංචි වීම සාර්ථකයි',
    'loginSuccessful': 'පිවිසීම සාර්ථකයි',
    'loginFailed': 'පිවිසීම අසාර්ථකයි',
    'networkError': 'ජාල දෝෂයක්',
    'somethingWentWrong': 'යම් දෝෂයක් සිදුවී ඇත',
    'thankYou': 'ස්තුතියි',
    'orderSubmittedSuccessfully': 'ඇණවුම සාර්ථකව ඉදිරිපත් කරන ලදී',
    'goHome': 'මුල් පිටුවට යන්න',
    
    // Grower Order Page
    'growerOrderPageTitle': 'ගොවියාගේ ඇණවුම් පිටුව',
    'orderDetails': 'ඇණවුම් තොරතුරු',
    'growerName': 'ගොවියාගේ නම',
    'teaVariety': 'තේ වර්ගය',
    'selectTeaVariety': 'තේ වර්ගය තෝරන්න',
    'quantity': 'ප්‍රමාණය',
    'quantityInKg': 'ප්‍රමාණය (කිලෝග්‍රෑම්)',
    'expectedDate': 'අපේක්ෂිත දිනය',
    'dateYouCanGiveHarvest': 'ඔබට අස්වනු ලබා දිය හැකි දිනය',
    'additionalNotes': 'අමතර සටහන්',
    'submitOrder': 'ඇණවුම ඉදිරිපත් කරන්න',
    'pleaseSelectTeaVariety': 'කරුණාකර තේ වර්ගය තෝරන්න',
    'pleaseEnterQuantity': 'කරුණාකර ප්‍රමාණය ඇතුළත් කරන්න',
    'pleaseEnterValidQuantity': 'කරුණාකර වලංගු ප්‍රමාණයක් ඇතුළත් කරන්න',
    'pleaseSelectDate': 'කරුණාකර දිනය තෝරන්න',
    'blackTea': 'කළු තේ',
    'greenTea': 'කොළ තේ',
    'whiteTea': 'සුදු තේ',
    'oolongTea': 'ඔලෝං තේ',
    
    // Feedback Page
    'feedbackPageTitle': 'ප්‍රතිපෝෂණ',
    'feedback': 'ප්‍රතිපෝෂණ',
    'rateYourExperience': 'ඔබේ අත්දැකීම ඇගයීමට ලක් කරන්න',
    'whatDescribesYourExperience': 'ඔබේ අත්දැකීම විස්තර කරන්නේ කුමක්ද',
    'additionalComments': 'අමතර අදහස්',
    'tellUsMoreAboutYourExperience': 'ඔබගේ අත්දැකීම ගැන තව දෙයක් අපට කියන්න',
    'goodQuality': 'හොඳ ගුණාත්මකභාවය',
    'onTime': 'වේලාවට',
    'greatCommunication': 'හොඳ සන්නිවේදනය',
    'delay': 'ප්‍රමාදය',
    'poorPackaging': 'නරක ඇසිරීම',
    'unresponsive': 'ප්‍රතිචාර නොදැක්වීම',
    'selected': 'තෝරාගත්',
    'yourFeedback': 'ඔබේ ප්‍රතිපෝෂණ',
    'pleaseTellUs': 'කරුණාකර ඔබේ අත්දැකීම් ගැන අපට කියන්න',
    'rating': 'ශ්‍රේණිගත කිරීම',
    'tags': 'ටැග්',
    'tapToAddTags': 'ටැග් එකතු කිරීම සඳහා ටැප් කරන්න',
    'submitFeedback': 'ප්‍රතිපෝෂණ ඉදිරිපත් කරන්න',
    'pleaseEnterFeedback': 'කරුණාකර ඔබේ ප්‍රතිපෝෂණ ඇතුළත් කරන්න',
    'pleaseFillAtLeastOneField': 'කරුණාකර අවම වශයෙන් එක් ක්ෂේත්‍රයක් පිරවන්න',
    'pleaseSelectRating': 'කරුණාකර ශ්‍රේණිගත කිරීමක් තෝරන්න',
    'feedbackSubmittedSuccessfully': 'ප්‍රතිපෝෂණ සාර්ථකව ඉදිරිපත් කරන ලදී',
    'failedToSaveFeedback': 'ප්‍රතිපෝෂණ සුරැකීමට අසමත් විය',
    'databaseError': 'දත්ත ගබඩාවේ දෝෂය',
    'service': 'සේවාව',
    'quality': 'ගුණත්වය',
    'price': 'මිල',
    'delivery': 'බෙදාහැරීම',
    'support': 'සහාය',

    //collector 

    "pleaseConfirmPassword": "කරුණාකර මුරපදය තහවුරු කරන්න",
    "passwordMismatch": "මුරපද නොගැලපේ",
    "signup": "ලියාපදිංචි වන්න",
    "harvestRequests": "අස්වැන්න ඉල්ලීම්",
     "paymentDetails": "ගෙවීම් විස්තර",
  "refNumber": "හැඳුනුම් අංකය",
  "amount": "මුදල",
  "status": "ගෙවීම් තත්ත්වය",
  "paymentDate": "ගෙවීම් දිනය",
  "nic": "ජාතික හැඳුනුම්පත් අංකය",
  "name": "නම",
  "phone": "දුරකථන අංකය",
  "notPaid": "ගෙවා නොමැත",
  "markAsPaid": "ගෙවා ඇති බව සලකුණු කරන්න",
  "paymentMarkedPaid": "ගෙවීම් ගෙවා ඇති බව සලකුණු කරන ලදී",
   "paymentHistory": "ගෙවීම් ඉතිහාසය",
  "noPaymentHistory": "ගෙවීම් ඉතිහාසය සොයාගත නොහැක.",
  "date": "දිනය",
  "collectorPayments": "සංග්‍රාහක\nගෙවීම්",
  "toPay": "ගෙවිය යුතු මුදල",
  "totalToPay": "සම්පූර්ණ ගෙවිය යුතු මුදල",
  "ref": "හැඳුනුම්",
   "personalDetails": "පුද්ගලික විස්තර",
  "edit": "සංස්කරණය කරන්න",
  "save": "සුරකින්න",
  "gender": "ලිංගය",
  "dob": "උපන් දිනය",
  "vehicleNumber": "වාහන අංකය",

  //collector login

  "signingUp": "ලියාපදිංචිය සිදු කරමින්...",
  "signupSuccess": "ලියාපදිංචිය සාර්ථකව සිදු කළා!",
  "signupFailed": "ලියාපදිංචිය අසාර්ථකයි:",
  "unknownError": "නොදනී දෝෂයක්",
  "connectionError": "සර්වරය හා සම්බන්ධ වීමට දෝෂයක්:",
  "fixErrors": "කරුණාකර ආකෘතිය සවි කරන්න",
  "emailLabel": "ඊ‑තැපැල්",
  "enterEmail": "කරුණාකර ඔබේ ඊ‑තැපැල් ඇතුළු කරන්න",
  "invalidEmail": "වලංගු ඊ‑තැපැල් ලිපිනයක් ලබා දෙන්න",
  "passwordLabel": "මුරපදය",
  "enterPassword": "කරුණාකර ඔබේ මුරපදය ඇතුළු කරන්න",
  "shortPassword": "මුරපදය අඩුමෙන් අකුරු හයකින් විය යුතුය",
  "confirmPasswordLabel": "මුරපදය තහවුරු කරන්න",
  "confirmPasswordRequired": "කරුණාකර මුරපදය තහවුරු කරන්න",
  "signUpButton": "ලියාපදිංචි වන්න",
  "signInToggle": "පිවිසෙන්න",
  "signUpToggle": "ලියාපදිංචි වන්න" ,

  //contact us


  "contactUsTitle": "අපව අමතන්න",
  "contactIntro": "ඔබේ ප්‍රශ්න සඳහා සහාය ලබාදීමට අපි සූදානම්. ඔබට යෝජනා, ප්‍රතිචාර හෝ අදාළ පණිවිඩ සඳහා අපව සම්බන්ධ කරගන්න.",
  "contactMethodsTitle": "ඔබ අපව සම්බන්ධ කරගත හැක්කේ මෙසේය,",
  "call": "ඇමතුම්",
  "whatsapp": "වට්සැප්",
  "navHome": "මුල් පිටුව",
  "navNotification": "දැනුම්දීම්",
  "navProfile": "පැතිකඩ",
  "navContactUs": "අපව අමතන්න",

  //fertilizer

  "fertilizerTitle": "පොහොර තොරතුරු",
  "totalFertilizer": "මුළු පොහොර",

  //grower

  "harvestSummaryTitle": "අවුල විස්තරය",
  "totalHarvest": "මුළු අවුල",
  "superTea": "සුපිරි තේ",
  "normalTea": "සාමාන්‍ය තේ",
  "teaQualityDistribution": "තේ තත්ත්ව බෙදාහැරීම",
  "growerHomeTitle": "මුල් පිටුව\nවගුරුවා",
  "navHelp": "උදව් මධ්‍යස්ථානය",
  "growerPaymentsTitle": "වගුරුවා ගෙවීම්",
  "totalPayment": "මුළු ගෙවීම",
  "paymentTime": "ගෙවීම් වේලාව",
  "paymentMethod": "ගෙවීම් ක්‍රමය",
  "noPayments": "ගෙවීම් දත්ත හමු නොවීය.",
  "helpCenterTitle": "උදව් මධ්‍යස්ථානය",
  "nicNumber": "ජාතික හැඳුනුම්පත් අංකය",
  "birthday": "උපන් දිනය",
  "updateSuccess": "විස්තර සක්‍රියව දියත් විය!",
  "updateFailed": "යාවත්කාලීන කිරීම අසාර්ථකයි.",
  "signInSuccess": "ඔබ සාර්ථකව පිවිසෙන්නට ලදි.",
  "bankDetails": "බැංකු විස්තර",
  "branch": "ශාඛාව",
  "holderName": "අයිතිකරුගේ නම",
  "submit": "ඉදිරිපත් කරන්න",
  "bankSuccess": "බැංකු විස්තර සුරකින්නට හැකි විය!",
  "bankFail": "බැංකු විස්තර සුරැකීමට අසාර්ථක විය",
  "fillFields": "කරුණාකර අවශ්‍ය සියලු ක්ෂේත්‍ර පුරවන්න",
  "fieldRequired": "මෙම ක්ෂේත්‍රය අවශ්‍යයි",
  "nicHint": "ජා.හැ.අංකය ඇතුළත් කරන්න",
  "addressLine1": "ලිපිනය පළමු පේළිය",
  "addressLine2": "ලිපිනය දෙවන පේළිය (විකල්ප)",
  "selectGender": "භාවය තෝරන්න",
  "selectMethod": "ක්‍රමය තෝරන්න",
  "create": "ගිණුම සාදන්න",
  "required": "අවශ්‍යයි",
  "invalidPhone": "වැරදි දුරකථන අංකය",
  "dobRequired": "උපන් දිනය තෝරන්න",
  "genderRequired": "භාවය තෝරන්න",
  "paymentRequired": "ගෙවීමේ ක්‍රමය තෝරන්න",
  "signInFail": "ඇතුල් වීමට අසමත් විය",
  "passwordLength": "මුරපදය අක්ෂර 6කින් වඩා වැඩි විය යුතුය",
  "confirmPasswordHint": "කරුණාකර ඔබේ මුරපදය තහවුරු කරන්න",
  "formError": "කරුණාකර ආකෘතියේ දෝෂ නිවැරදි කරන්න",
  "requestOrderDescription": "ආසන්න ප්‍රජාවකින් රැඳවන්නාගෙන් ලබාගන්න ඉල්ලීමක් කරන්න",
  "requestOrder": "ඇණවුම ඉල්ලන්න",
  "notification": "දැනුම්දීම්",
  "quantityKg": "කිලෝ ගණන:",
  "superLeafKg": "සුපිරි කොළ (kg)",
  "greenLeafKg": "කොළ කොළ (kg)",
  "harvestDate": "ඔබට අස්වැන්න ලබා දිය හැකි දිනය:",
  "transportMethod": "ප්‍රවාහනය කරන ආකාරය:",
  "saveOrder": "ඇණවුම සුරකින්න",
  "completeAllFields": "කරුණාකර සියලු ක්ෂේත්‍ර පුරවන්න",
  "orderSaved": "ඇණවුම සාර්ථකව සුරකින ලදි!",
  "orderFailed": "ඇණවුම සුරැකීම අසාර්ථක විය",
  "selectDate": "දිනය තෝරන්න",
  "orders": "ඇණවුම්",

  //notification

  "today": "අද",
  "earlier": "පෙර",
  "contact": "සම්බන්ධ වන්න",

  //grower account

  "editGrower": "ගොවියා සංස්කරණය කරන්න",
  "enterFirstName": "මුල් නම ඇතුළත් කරන්න",
  "enterLastName": "අවසන් නම ඇතුළත් කරන්න",
  "saveChanges": "වෙනස්කම් සුරකින්න",

  //other

  "orderSuccessMessage": "ඔබ සාර්ථකව පුරනය වී ඇත!",
  "harvestTitle": "අස්වැන්න",
  "navigateAddHarvest": "අලුත් ඵලයක් එකතු කිරීමේ තිරයට යන්න",
  "settingsNotImplemented": "සැකසුම් තවම ක්‍රියාත්මක කර නැත",
  "monthly": "මාසික",
  "annually": "වාර්ෂික",
  "monthlyOverview": "මාසික සාරාංශය",
  "annuallyOverview": "වාර්ෂික සාරාංශය",
  "yourWeight": "ඔබේ බර",
  "noDataAvailable": "දත්ත නැත",
  "motivationalMessage": "ඔබ ඉතා හොඳින් කරමින් සිටී!",
  "placeholderDots": "...",
  "navNotifications": "දැනුම්දීම්",
  "bankTransfer": "බැංකු හරහා මාරු කිරීම",
  "fabNotImplemented": "FAB ක්‍රියාව ක්‍රියාත්මක කර නොමැත",
  "growerOrderTitle": "නව ඇණවුම",
  "howManyKg": "ඇතේ කීලෝවක්ද (kg):",
  "superLeafHint": "සුපිරි කොළ (kg)",
  "enterSuperLeaf": "සුපිරි කොළ බර ඇතුළත් කරන්න",
  "greenLeafHint": "කොළ කොළය (kg)",
  "enterGreenLeaf": "කොළ කොළ බර ඇතුළත් කරන්න",
  "dateYouCanGive": "ඔබට ඵලය ලබා දිය හැකි දිනය:",
  "pleasePickDate": "කරුණාකර දිනයක් තෝරන්න",
  "howToTransport": "ප්‍රවාහනය කරන්නේ කෙසේද:",
  "pleaseSelectTransport": "කරුණාකර ප්‍රවාහන ක්‍රමය තෝරන්න",
  "completeFields": "කරුණාකර සියලු ක්ෂේත්‍ර පුරවන්න",
  "orderSaveFailed": "ඇණවුම සුරැකීමට අසාර්ථක විය",
  "navOrders": "ඇණවුම්"
  
  };

  // Tamil Strings
  static const Map<String, String> tamil = {
    // Common
    'loading': 'ஏற்றுகிறது...',
    'error': 'பிழை',
    'success': 'வெற்றி',
    
    // Welcome Pages  
    'getReady': 'தயாராகுங்கள்',
    'newJourney': 'புதிய பயணம்',
    'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'termsOfService': 'சேவை நிபந்தனைகள்',
    'termsConditions': 'தொழிற்சாலையுடன் இணைந்த பதிவு செய்யப்பட்ட சேகரிப்பாளர்கள், இலங்கை தேயிலை வாரியத்தால் அங்கீகரிக்கப்பட்ட வியாபாரிகள் மற்றும் அங்கீகரிக்கப்பட்ட தேயிலை விவசாயிகள் சப்ளையர்களாக பதிவு செய்ய தகுதியுடையவர்கள்.\n\nதகுதி பெற, அந்தந்த தொழிற்சாலை மற்றும் இலங்கை தேயிலை வாரியத்தால் முன்னரே தீர்மானிக்கப்பட்ட விவரக்குறிப்புகள் மற்றும் தரத் தரநிலைகளை பூர்த்தி செய்யும் திறனை அவர்கள் நிரூபிக்க வேண்டும்.',
    'acceptContinue': 'ஏற்று தொடரவும்',
    'youAreA': 'நீங்கள் ஒரு',
    'grower': 'விவசாயி',
    'collector': 'சேகரிப்பாளர்',
    'next': 'அடுத்து',
    'pleaseSelectRole': 'தயவுசெய்து உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
    'harvestDetailsReceived': 'உங்கள் அறுவடை\nவிவரங்கள் கிடைத்தன.',
    'continue': 'தொடர்க',
    'settings': 'அமைப்புகள்',
    'darkMode': 'இருண்ட பயன்முறை',
    'language': 'மொழி',
    'close': 'மூடு',
    'asACollector':'ஒரு சேகரிப்பாளராக',
    'letsStart': 'நமக்கு தொடங்குவோம்',
    'asAGrower':'ஒரு விவசாயியாக',
    
    // Common UI Elements
    'signIn': 'உள்நுழைக',
    'signUp': 'பதிவு செய்க',
    'email': 'மின்னஞ்சல்',
    'password': 'கடவுச்சொல்',
    'confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'forgotPassword': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'createAccount': 'கணக்கை உருவாக்கவும்',
    'alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'dontHaveAccount': 'கணக்கு இல்லையா?',
    'login': 'உள்நுழைவு',
    'logout': 'வெளியேறு',
    
    // Navigation
    'home_page_title': 'முதல் பக்கம்\nவிவசாயி',
    'home': 'முகப்பு',
    'harvest': 'அறுவடை',
    'payments': 'பணம் செலுத்துதல்',
    'profile': 'சுயவிவரம்',
    'helpCenter': 'உதவி மையம்',
    'notifications': 'அறிவிப்புகள்',
    'contactUs': 'எங்களை தொடர்பு கொள்ளவும்',
    
    // Help Center
    'fertilizer': 'உரம்',
    'loans': 'கடன்கள்',
    'insurance': 'காப்பீடு',
    'weatherForecast': 'வானிலை முன்னறிவிப்பு',
    'marketPrices': 'சந்தை விலைகள்',
    
    // Form Fields
    'firstName': 'முதல் பெயர்',
    'lastName': 'கடைசி பெயர்',
    'fullName': 'முழு பெயர்',
    'phoneNumber': 'தொலைபேசி எண்',
    'address': 'முகவரி',
    'city': 'நகரம்',
    'postalCode': 'அஞ்சல் குறியீடு',
    'bankName': 'வங்கியின் பெயர்',
    'branchName': 'கிளையின் பெயர்',
    'accountNumber': 'கணக்கு எண்',
    'accountHolder': 'கணக்கு வைத்திருப்பவர்',
    
    // Messages
    'pleaseEnterEmail': 'தயவுசெய்து உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'pleaseEnterValidEmail': 'தயவுசெய்து சரியான மின்னஞ்சலை உள்ளிடவும்',
    'pleaseEnterPassword': 'தயவுசெய்து உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'passwordTooShort': 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்களாக இருக்க வேண்டும்',
    'passwordsDontMatch': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'registrationSuccessful': 'பதிவு வெற்றிகரமானது',
    'loginSuccessful': 'உள்நுழைவு வெற்றிகரமானது',
    'loginFailed': 'உள்நுழைவு தோல்வியுற்றது',
    'networkError': 'நெட்வொர்க் பிழை',
    'somethingWentWrong': 'ஏதோ தவறு நடந்தது',
    'thankYou': 'நன்றி',
    'orderSubmittedSuccessfully': 'ஆர்டர் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது',
    'goHome': 'வீட்டுக்கு செல்',
    
    // Grower Order Page
    'growerOrderPageTitle': 'விவசாயி ஆர்டர் பக்கம்',
    'orderDetails': 'ஆர்டர் விவரங்கள்',
    'growerName': 'விவசாயியின் பெயர்',
    'teaVariety': 'தேயிலை வகை',
    'selectTeaVariety': 'தேயிலை வகையைத் தேர்ந்தெடுக்கவும்',
    'quantity': 'அளவு',
    'quantityInKg': 'அளவு (கிலோகிராம்)',
    'expectedDate': 'எதிர்பார்க்கப்படும் தேதி',
    'dateYouCanGiveHarvest': 'நீங்கள் அறுவடை கொடுக்கக்கூடிய தேதி',
    'additionalNotes': 'கூடுதல் குறிப்புகள்',
    'submitOrder': 'ஆர்டரைச் சமர்ப்பிக்கவும்',
    'pleaseSelectTeaVariety': 'தயவுசெய்து தேயிலை வகையைத் தேர்ந்தெடுக்கவும்',
    'pleaseEnterQuantity': 'தயவுசெய்து அளவை உள்ளிடவும்',
    'pleaseEnterValidQuantity': 'தயவுசெய்து சரியான அளவை உள்ளிடவும்',
    'pleaseSelectDate': 'தயவுசெய்து தேதியைத் தேர்ந்தெடுக்கவும்',
    'blackTea': 'கருப்பு தேயிலை',
    'greenTea': 'பச்சை தேயிலை',
    'whiteTea': 'வெள்ளை தேயிலை',
    'oolongTea': 'ஓலாங் தேயிலை',
    
    // Feedback Page
    'feedbackPageTitle': 'கருத்து',
    'feedback': 'கருத்து',
    'rateYourExperience': 'உங்கள் அனுபவத்தை மதிப்பிடவும்',
    'whatDescribesYourExperience': 'உங்கள் அனுபவத்தை என்ன விவரிக்கிறது',
    'additionalComments': 'கூடுதல் கருத்துகள்',
    'tellUsMoreAboutYourExperience': 'உங்கள் அனுபவத்தைப் பற்றி மேலும் எங்களிடம் சொல்லுங்கள்',
    'goodQuality': 'நல்ல தரம்',
    'onTime': 'நேரத்திற்கு',
    'greatCommunication': 'சிறந்த தொடர்பு',
    'delay': 'தாமதம்',
    'poorPackaging': 'மோசமான பேக்கேஜிங்',
    'unresponsive': 'பதிலளிக்காதது',
    'selected': 'தேர்ந்தெடுக்கப்பட்டது',
    'yourFeedback': 'உங்கள் கருத்து',
    'pleaseTellUs': 'தயவுசெய்து உங்கள் அனுபவத்தைப் பற்றி எங்களிடம் சொல்லுங்கள்',
    'rating': 'மதிப்பீடு',
    'tags': 'டேக்குகள்',
    'tapToAddTags': 'டேக்குகளைச் சேர்க்க டேப் செய்யவும்',
    'submitFeedback': 'கருத்தைச் சமர்ப்பிக்கவும்',
    'pleaseEnterFeedback': 'தயவுசெய்து உங்கள் கருத்தை உள்ளிடவும்',
    'pleaseFillAtLeastOneField': 'தயவுசெய்து குறைந்தபட்சம் ஒரு புலத்தை நிரப்பவும்',
    'pleaseSelectRating': 'தயவுசெய்து மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்',
    'feedbackSubmittedSuccessfully': 'கருத்து வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது',
    'failedToSaveFeedback': 'கருத்தை சேமிப்பதில் தோல்வி',
    'databaseError': 'தரவுத்தள பிழை',
    'service': 'சேவை',
    'quality': 'தரம்',
    'price': 'விலை',
    'delivery': 'விநியோகம்',
    'support': 'ஆதரவு',

   //collector signup

  "pleaseConfirmPassword": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
  "passwordMismatch": "கடவுச்சொற்கள் பொருந்தவில்லை",
  "signup": "பதிவு செய்யவும்",
  "harvestRequests": "அறுவடை கோரிக்கைகள்",
   "paymentDetails": "பணம் செலுத்தல் விவரங்கள்",
  "refNumber": "குறிப்பு எண்",
  "amount": "தொகை",
  "status": "பணம் செலுத்தல் நிலை",
  "paymentDate": "பணம் செலுத்திய தேதி",
  "nic": "தேசிய அடையாள அட்டை எண்",
  "name": "பெயர்",
  "phone": "தொலைபேசி எண்",
  "notPaid": "பணம் செலுத்தவில்லை",
  "markAsPaid": "பணம் செலுத்தியதாக குறிக்கவும்",
  "paymentMarkedPaid": "பணம் செலுத்தியதாக குறிக்கப்பட்டது",
  "paymentHistory": "பணம் செலுத்தல் வரலாறு",
  "noPaymentHistory": "பணம் செலுத்தல் வரலாறு இல்லை.",
  "date": "தேதி",
  "collectorPayments": "கலெக்டர்\nகட்டணங்கள்",
  "toPay": "செலுத்த வேண்டியது",
  "totalToPay": "மொத்தம் செலுத்த வேண்டியது",
  "ref": "குறிப்பு",
   "personalDetails": "தனிப்பட்ட விவரங்கள்",
  "edit": "தொகுக்கவும்",
  "save": "சேமிக்கவும்",
  "gender": "பாலினம்",
  "dob": "பிறந்த தேதி",
  "vehicleNumber": "வாகன எண்",

  //collector login

   "signingUp": "பதிவு செய்கிறது...",
  "signupSuccess": "பதிவு வெற்றிகரமாக முடிந்தது!",
  "signupFailed": "பதிவு தோல்வியடைந்தது:",
  "unknownError": "எதரப்படாத பிழை",
  "connectionError": "சேவையகத்துடன் இணைப்பதில் பிழை:",
  "fixErrors": "தட்டத்தில் உள்ள பிழைகள் திருத்தவும்",
  "emailLabel": "மின்னஞ்சல்",
  "enterEmail": "தயவுசெய்து உங்கள் மின்னஞ்சலை உள்ளிடவும்",
  "invalidEmail": "தயவுசெய்து செல்லுபடியான மின்னஞ்சல் முகவரியை உள்ளிடவும்",
  "passwordLabel": "கடவுச்சொல்",
  "enterPassword": "தயவுசெய்து உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
  "shortPassword": "கடவுச்சொல் குறைந்த பட்சம் 6 எழுத்துகள் இருக்க வேண்டும்",
  "confirmPasswordLabel": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
  "confirmPasswordRequired": "தயவுசெய்து உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்",
  "signUpButton": "பதிவு செய்",
  "signInToggle": "உள் நுழை",
  "signUpToggle": "பதிவு செய்",

  //contact us

  "contactUsTitle": "எங்களை தொடர்பு கொள்ள",
  "contactIntro": "உங்கள் சந்தேகங்கள் அல்லது கோரிக்கைகளுக்கு உதவ எங்களிடம் அணுகவும். மேலதிக தகவலுக்கு எங்களை தொடர்பு கொள்ளுங்கள்.",
  "contactMethodsTitle": "நீங்கள் எங்களைத் தொடர்புகொள்ளலாம்,",
  "call": "அழைப்பு",
  "whatsapp": "வாட்ஸ்அப்",
  "navHome": "முகப்பு",
  "navNotification": "அறிவிப்புகள்",
  "navProfile": "சுயவிவரம்",
  "navContactUs": "தொடர்பு கொள்ள",

  //fertilizer

  "fertilizerTitle": "உரம்",
  "totalFertilizer": "மொத்த உரம்",
 
  //grower

  "harvestSummaryTitle": "விளைச்சல் சுருக்கம்",
  "totalHarvest": "மொத்த விளைச்சல்",
  "superTea": "சூப்பர் தேநீர்",
  "normalTea": "இயல்பான தேநீர்",
  "teaQualityDistribution": "தேயிலை தர விநியோகம்",
   "growerHomeTitle": "முகப்பு பக்கம்\nவிவசாயி",
  "navHelp": "உதவி மையம்",
  "growerPaymentsTitle": "விவசாயி கட்டணங்கள்",
  "totalPayment": "மொத்த கட்டணம்",
  "paymentTime": "கட்டணம் செலுத்திய நேரம்",
  "paymentMethod": "கட்டணம் விதிமுறை",
  "noPayments": "பணம் தொடர்பான தரவு இல்லை.",
  "helpCenterTitle": "உதவி மையம்",
  "nicNumber": "ஐ.டி அட்டை எண்",
  "birthday": "பிறந்தநாள்",
  "updateSuccess": "விவரங்கள் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!",
  "updateFailed": "புதுப்பிப்பு தோல்வியுற்றது.",
  "signInSuccess": "நீங்கள் வெற்றிகரமாக உள்நுழைந்துள்ளீர்கள்.",
  "bankDetails": "வங்கிக் விவரங்கள்",
  "branch": "கிளை",
  "holderName": "கணக்கு வைத்திருப்பவரின் பெயர்",
  "submit": "சமர்ப்பிக்கவும்",
  "bankSuccess": "வங்கிக் விவரங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன!",
  "bankFail": "வங்கிக் விவரங்களை சேமிக்க முடியவில்லை",
  "fillFields": "தயவுசெய்து தேவையான அனைத்து விவரங்களையும் பூர்த்தி செய்யவும்",
  "fieldRequired": "இந்த புலம் தேவைப்படுகிறது",
  "nicHint": "அடையாள எண்ணை உள்ளிடவும்",
  "addressLine1": "முகவரி வரி 1",
  "addressLine2": "முகவரி வரி 2 (விருப்பம்)",
  "selectGender": "பாலினத்தைத் தேர்வுசெய்க",
  "selectMethod": "முறையை தேர்ந்தெடுக்கவும்",
  "create": "கணக்கை உருவாக்கவும்",
  "required": "தேவைப்படுகிறது",
  "invalidPhone": "தவறான தொலைபேசி எண்",
  "dobRequired": "பிறந்த தேதியைத் தேர்ந்தெடுக்கவும்",
  "genderRequired": "பாலினத்தைத் தேர்ந்தெடுக்கவும்",
  "paymentRequired": "பணம் பெறும் முறையைத் தேர்ந்தெடுக்கவும்",
  "signInFail": "உள்நுழைய முடியவில்லை",
  "passwordLength": "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்",
  "confirmPasswordHint": "தயவுசெய்து உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்",
  "formError": "தயவுசெய்து படிவத்தில் உள்ள பிழைகளை சரிசெய்யவும்",
  "requestOrderDescription": "அருகிலுள்ள சமூகத்திலிருந்து சேகரிப்பவரை பெற கோரிக்கை விடுக்கவும்",
  "requestOrder": "ஆர்டர் கோரிக்கை",
  "notification": "அறிவிப்புகள்",
  "quantityKg": "எத்தனை கிலோ (kg):",
  "superLeafKg": "சூப்பர் இலை (kg)",
  "greenLeafKg": "பச்சை இலை (kg)",
  "harvestDate": "நீங்கள் கொளுத்த முடியும் தேதி:",
  "transportMethod": "எப்படி எடுத்துச்செல்ல வேண்டும்:",
  "saveOrder": "ஆர்டரை சேமிக்கவும்",
  "completeAllFields": "அனைத்து புலங்களையும் பூர்த்தி செய்யவும்",
  "orderSaved": "ஆர்டர் வெற்றிகரமாக சேமிக்கப்பட்டது!",
  "orderFailed": "ஆர்டர் சேமிக்க முடியவில்லை",
  "selectDate": "தேதியைத் தேர்ந்தெடுக்கவும்",
  "orders": "ஆர்டர்கள்",


  //notification

  "today": "இன்று",
  "earlier": "முன்னதாக",
  "contact": "தொடர்பு கொள்ள",


//grower account

  "editGrower": "விவசாயியைத் திருத்தவும்",
  "enterFirstName": "முதல் பெயரை உள்ளிடவும்", 
  "enterLastName": "கடைசி பெயரை உள்ளிடவும்",
  "saveChanges": "மாற்றங்களைச் சேமிக்கவும்",

  //other

  
  "orderSuccessMessage": "நீங்கள் வெற்றிகரமாக உள்நுழைந்தீர்கள்!",
  "harvestTitle": "பயிர்",
  "navigateAddHarvest": "புதிய பயிர் சேர்க்கும் திரைக்கு செல்லவும்",
  "settingsNotImplemented": "அமைப்புகள் இன்னும் செயல்படுத்தப்படவில்லை",
  "monthly": "மாதந்தோறும்",
  "annually": "ஆண்டு",
  "monthlyOverview": "மாத நிலை காணொளி",
  "annuallyOverview": "ஆண்டு நிலை காணொளி",
  "yourWeight": "உங்கள் எடை",
  "noDataAvailable": "தரவு இல்லை",
  "motivationalMessage": "நீங்கள் சிறப்பாக செய்கிறீர்கள்!",
  "placeholderDots": "...",
  "navNotifications": "அறிவிப்புகள்",
  "bankTransfer": "வங்கித் பரிமாற்றம்",
  "fabNotImplemented": "FAB செயல்பாடு செயல்படுத்தப்படவில்லை",
  "growerOrderTitle": "புதிய ஆர்டர்",
  "howManyKg": "எத்தனை (கிலோ):",
  "superLeafHint": "சூப்பர் இலை (kg)",
  "enterSuperLeaf": "சூப்பர் இலை எடை உள்ளிடவும்",
  "greenLeafHint": "பச்சை இலை (kg)",
  "enterGreenLeaf": "பச்சை இலை எடை உள்ளிடவும்",
  "dateYouCanGive": "பயிர் வழங்கும் தேதி:",
  "pleasePickDate": "தேதியைத் தேர்ந்தெடுக்கவும்",
  "howToTransport": "எப்படி போக்குவரத்து செய்ய வேண்டும்:",
  "pleaseSelectTransport": "போக்குவரத்து முறையைத் தேர்ந்தெடுக்கவும்",
  "completeFields": "அனைத்து புலங்களையும் நிரப்பவும்",
  "orderSaveFailed": "ஆர்டரை சேமிக்க முடியவில்லை",
  "navOrders": "ஆர்டர்கள்"

  };
}
