class AppStrings {
  // English Strings
  static const Map<String, String> english = {
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    
    // Welcome Pages  
    'getReady': 'Get ready for',
    'newJourney': 'New Journey',
    'selectLanguage': 'Select Language',
    
    // Common UI Elements
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot Password?',
    'createAccount': 'Create Account',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccount': "Don't have an account?",
    'login': 'Login',
    'logout': 'Logout',
    
    // Navigation
    'home_page_title': 'Home Page\nGrower',
    'home': 'Home',
    'harvest': 'Harvest',
    'payments': 'Payments',
    'profile': 'Profile',
    'helpCenter': 'Help Center',
    'notifications': 'Notifications',
    'contactUs': 'Contact Us',
    
    // Form Fields
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'fullName': 'Full Name',
    'phoneNumber': 'Phone Number',
    'address': 'Address',
    'city': 'City',
    'postalCode': 'Postal Code',
    'bankName': 'Bank Name',
    'branchName': 'Branch Name',
    'accountNumber': 'Account Number',
    'accountHolder': 'Account Holder Name',
    
    // Messages
    'pleaseEnterEmail': 'Please enter your email',
    'pleaseEnterValidEmail': 'Please enter a valid email',
    'pleaseEnterPassword': 'Please enter your password',
    'passwordTooShort': 'Password must be at least 6 characters',
    'passwordsDontMatch': 'Passwords do not match',
    'registrationSuccessful': 'Registration Successful',
    'loginSuccessful': 'Login Successful',
    'loginFailed': 'Login Failed',
    'networkError': 'Network Error',
    'somethingWentWrong': 'Something went wrong',
    'thankYou': 'Thank You',
    'orderSubmittedSuccessfully': 'Order submitted successfully',
    'goHome': 'Go Home',
    
    // Grower Order Page
    'growerOrderPageTitle': 'Grower Order Page',
    'orderDetails': 'Order Details',
    'growerName': 'Grower Name',
    'teaVariety': 'Tea Variety',
    'selectTeaVariety': 'Select Tea Variety',
    'quantity': 'Quantity',
    'quantityInKg': 'Quantity (in kg)',
    'expectedDate': 'Expected Date',
    'dateYouCanGiveHarvest': 'Date you can give harvest',
    'additionalNotes': 'Additional Notes',
    'submitOrder': 'Submit Order',
    'pleaseSelectTeaVariety': 'Please select tea variety',
    'pleaseEnterQuantity': 'Please enter quantity',
    'pleaseEnterValidQuantity': 'Please enter valid quantity',
    'pleaseSelectDate': 'Please select date',
    'blackTea': 'Black Tea',
    'greenTea': 'Green Tea',
    'whiteTea': 'White Tea',
    'oolongTea': 'Oolong Tea',
    
    // Feedback Page
    'feedbackPageTitle': 'Feedback',
    'yourFeedback': 'Your Feedback',
    'pleaseTellUs': 'Please tell us about your experience',
    'rating': 'Rating',
    'tags': 'Tags',
    'tapToAddTags': 'Tap to add tags',
    'submitFeedback': 'Submit Feedback',
    'pleaseEnterFeedback': 'Please enter your feedback',
    'pleaseSelectRating': 'Please select rating',
    'feedbackSubmittedSuccessfully': 'Feedback submitted successfully',
    'service': 'Service',
    'quality': 'Quality',
    'price': 'Price',
    'delivery': 'Delivery',
    'support': 'Support',
  };

  // Sinhala Strings
  static const Map<String, String> sinhala = {
    // Common
    'loading': 'පූරණය වෙමින්...',
    'error': 'වරදක්',
    'success': 'සාර්ථකයි',
    
    // Welcome Pages  
    'getReady': 'සූදානම් වන්න',
    'newJourney': 'නව ගමන',
    'selectLanguage': 'භාෂාව තෝරන්න',
    
    // Common UI Elements
    'signIn': 'පිවිසෙන්න',
    'signUp': 'ලියාපදිංචි වෙන්න',
    'email': 'ඊමේල්',
    'password': 'මුරපදය',
    'confirmPassword': 'මුරපදය තහවුරු කරන්න',
    'forgotPassword': 'මුරපදය අමතකද?',
    'createAccount': 'ගිණුමක් සාදන්න',
    'alreadyHaveAccount': 'දැනටමත් ගිණුමක් තිබේද?',
    'dontHaveAccount': 'ගිණුමක් නැද්ද?',
    'login': 'පිවිසීම',
    'logout': 'ඉවත්වීම',
    
    // Navigation
    'home_page_title': 'මුල් පිටුව\nගොවියා',
    'home': 'මුල් පිටුව',
    'harvest': 'අස්වැන්න',
    'payments': 'ගෙවීම්',
    'profile': 'පැතිකඩ',
    'helpCenter': 'උදව් මධ්‍යස්ථානය',
    'notifications': 'දැනුම්දීම්',
    'contactUs': 'අප හා සම්බන්ධ වන්න',
    
    // Form Fields
    'firstName': 'මුල් නම',
    'lastName': 'අවසාන නම',
    'fullName': 'සම්පූර්ණ නම',
    'phoneNumber': 'දුරකථන අංකය',
    'address': 'ලිපිනය',
    'city': 'නගරය',
    'postalCode': 'තැපැල් කේතය',
    'bankName': 'බැංකුවේ නම',
    'branchName': 'ශාඛාවේ නම',
    'accountNumber': 'ගිණුම් අංකය',
    'accountHolder': 'ගිණුම්කරුගේ නම',
    
    // Messages
    'pleaseEnterEmail': 'කරුණාකර ඔබේ ඊමේල් ඇතුළත් කරන්න',
    'pleaseEnterValidEmail': 'කරුණාකර වලංගු ඊමේල් ඇතුළත් කරන්න',
    'pleaseEnterPassword': 'කරුණාකර ඔබේ මුරපදය ඇතුළත් කරන්න',
    'passwordTooShort': 'මුරපදය අවම වශයෙන් අක්ෂර 6 ක් විය යුතුය',
    'passwordsDontMatch': 'මුරපද නොගැළපේ',
    'registrationSuccessful': 'ලියාපදිංචි වීම සාර්ථකයි',
    'loginSuccessful': 'පිවිසීම සාර්ථකයි',
    'loginFailed': 'පිවිසීම අසාර්ථකයි',
    'networkError': 'ජාල දෝෂයක්',
    'somethingWentWrong': 'යම් දෝෂයක් සිදුවී ඇත',
    'thankYou': 'ස්තුතියි',
    'orderSubmittedSuccessfully': 'ඇණවුම සාර්ථකව ඉදිරිපත් කරන ලදී',
    'goHome': 'මුල් පිටුවට යන්න',
    
    // Grower Order Page
    'growerOrderPageTitle': 'ගොවියාගේ ඇණවුම් පිටුව',
    'orderDetails': 'ඇණවුම් තොරතුරු',
    'growerName': 'ගොවියාගේ නම',
    'teaVariety': 'තේ වර්ගය',
    'selectTeaVariety': 'තේ වර්ගය තෝරන්න',
    'quantity': 'ප්‍රමාණය',
    'quantityInKg': 'ප්‍රමාණය (කිලෝග්‍රෑම්)',
    'expectedDate': 'අපේක්ෂිත දිනය',
    'dateYouCanGiveHarvest': 'ඔබට අස්වනු ලබා දිය හැකි දිනය',
    'additionalNotes': 'අමතර සටහන්',
    'submitOrder': 'ඇණවුම ඉදිරිපත් කරන්න',
    'pleaseSelectTeaVariety': 'කරුණාකර තේ වර්ගය තෝරන්න',
    'pleaseEnterQuantity': 'කරුණාකර ප්‍රමාණය ඇතුළත් කරන්න',
    'pleaseEnterValidQuantity': 'කරුණාකර වලංගු ප්‍රමාණයක් ඇතුළත් කරන්න',
    'pleaseSelectDate': 'කරුණාකර දිනය තෝරන්න',
    'blackTea': 'කළු තේ',
    'greenTea': 'කොළ තේ',
    'whiteTea': 'සුදු තේ',
    'oolongTea': 'ඔලෝං තේ',
    
    // Feedback Page
    'feedbackPageTitle': 'ප්‍රතිපෝෂණ',
    'yourFeedback': 'ඔබේ ප්‍රතිපෝෂණ',
    'pleaseTellUs': 'කරුණාකර ඔබේ අත්දැකීම් ගැන අපට කියන්න',
    'rating': 'ශ්‍රේණිගත කිරීම',
    'tags': 'ටැග්',
    'tapToAddTags': 'ටැග් එකතු කිරීම සඳහා ටැප් කරන්න',
    'submitFeedback': 'ප්‍රතිපෝෂණ ඉදිරිපත් කරන්න',
    'pleaseEnterFeedback': 'කරුණාකර ඔබේ ප්‍රතිපෝෂණ ඇතුළත් කරන්න',
    'pleaseSelectRating': 'කරුණාකර ශ්‍රේණිගත කිරීමක් තෝරන්න',
    'feedbackSubmittedSuccessfully': 'ප්‍රතිපෝෂණ සාර්ථකව ඉදිරිපත් කරන ලදී',
    'service': 'සේවාව',
    'quality': 'ගුණත්වය',
    'price': 'මිල',
    'delivery': 'බෙදාහැරීම',
    'support': 'සහාය',
  };

  // Tamil Strings
  static const Map<String, String> tamil = {
    // Common
    'loading': 'ஏற்றுகிறது...',
    'error': 'பிழை',
    'success': 'வெற்றி',
    
    // Welcome Pages  
    'getReady': 'தயாராகுங்கள்',
    'newJourney': 'புதிய பயணம்',
    'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    
    // Common UI Elements
    'signIn': 'உள்நுழைக',
    'signUp': 'பதிவு செய்க',
    'email': 'மின்னஞ்சல்',
    'password': 'கடவுச்சொல்',
    'confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'forgotPassword': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'createAccount': 'கணக்கை உருவாக்கவும்',
    'alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'dontHaveAccount': 'கணக்கு இல்லையா?',
    'login': 'உள்நுழைவு',
    'logout': 'வெளியேறு',
    
    // Navigation
    'home_page_title': 'முதல் பக்கம்\nவிவசாயி',
    'home': 'முகப்பு',
    'harvest': 'அறுவடை',
    'payments': 'பணம் செலுத்துதல்',
    'profile': 'சுயவிவரம்',
    'helpCenter': 'உதவி மையம்',
    'notifications': 'அறிவிப்புகள்',
    'contactUs': 'எங்களை தொடர்பு கொள்ளவும்',
    
    // Form Fields
    'firstName': 'முதல் பெயர்',
    'lastName': 'கடைசி பெயர்',
    'fullName': 'முழு பெயர்',
    'phoneNumber': 'தொலைபேசி எண்',
    'address': 'முகவரி',
    'city': 'நகரம்',
    'postalCode': 'அஞ்சல் குறியீடு',
    'bankName': 'வங்கியின் பெயர்',
    'branchName': 'கிளையின் பெயர்',
    'accountNumber': 'கணக்கு எண்',
    'accountHolder': 'கணக்கு வைத்திருப்பவர்',
    
    // Messages
    'pleaseEnterEmail': 'தயவுசெய்து உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'pleaseEnterValidEmail': 'தயவுசெய்து சரியான மின்னஞ்சலை உள்ளிடவும்',
    'pleaseEnterPassword': 'தயவுசெய்து உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'passwordTooShort': 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்களாக இருக்க வேண்டும்',
    'passwordsDontMatch': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'registrationSuccessful': 'பதிவு வெற்றிகரமானது',
    'loginSuccessful': 'உள்நுழைவு வெற்றிகரமானது',
    'loginFailed': 'உள்நுழைவு தோல்வியுற்றது',
    'networkError': 'நெட்வொர்க் பிழை',
    'somethingWentWrong': 'ஏதோ தவறு நடந்தது',
    'thankYou': 'நன்றி',
    'orderSubmittedSuccessfully': 'ஆர்டர் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது',
    'goHome': 'வீட்டுக்கு செல்',
    
    // Grower Order Page
    'growerOrderPageTitle': 'விவசாயி ஆர்டர் பக்கம்',
    'orderDetails': 'ஆர்டர் விவரங்கள்',
    'growerName': 'விவசாயியின் பெயர்',
    'teaVariety': 'தேயிலை வகை',
    'selectTeaVariety': 'தேயிலை வகையைத் தேர்ந்தெடுக்கவும்',
    'quantity': 'அளவு',
    'quantityInKg': 'அளவு (கிலோகிராம்)',
    'expectedDate': 'எதிர்பார்க்கப்படும் தேதி',
    'dateYouCanGiveHarvest': 'நீங்கள் அறுவடை கொடுக்கக்கூடிய தேதி',
    'additionalNotes': 'கூடுதல் குறிப்புகள்',
    'submitOrder': 'ஆர்டரைச் சமர்ப்பிக்கவும்',
    'pleaseSelectTeaVariety': 'தயவுசெய்து தேயிலை வகையைத் தேர்ந்தெடுக்கவும்',
    'pleaseEnterQuantity': 'தயவுசெய்து அளவை உள்ளிடவும்',
    'pleaseEnterValidQuantity': 'தயவுசெய்து சரியான அளவை உள்ளிடவும்',
    'pleaseSelectDate': 'தயவுசெய்து தேதியைத் தேர்ந்தெடுக்கவும்',
    'blackTea': 'கருப்பு தேயிலை',
    'greenTea': 'பச்சை தேயிலை',
    'whiteTea': 'வெள்ளை தேயிலை',
    'oolongTea': 'ஓலாங் தேயிலை',
    
    // Feedback Page
    'feedbackPageTitle': 'கருத்து',
    'yourFeedback': 'உங்கள் கருத்து',
    'pleaseTellUs': 'தயவுசெய்து உங்கள் அனுபவத்தைப் பற்றி எங்களிடம் சொல்லுங்கள்',
    'rating': 'மதிப்பீடு',
    'tags': 'டேக்குகள்',
    'tapToAddTags': 'டேக்குகளைச் சேர்க்க டேப் செய்யவும்',
    'submitFeedback': 'கருத்தைச் சமர்ப்பிக்கவும்',
    'pleaseEnterFeedback': 'தயவுசெய்து உங்கள் கருத்தை உள்ளிடவும்',
    'pleaseSelectRating': 'தயவுசெய்து மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்',
    'feedbackSubmittedSuccessfully': 'கருத்து வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது',
    'service': 'சேவை',
    'quality': 'தரம்',
    'price': 'விலை',
    'delivery': 'விநியோகம்',
    'support': 'ஆதரவு',
  };
}
