// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test2API.Data;

#nullable disable

namespace test2API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("test2API.Models.GrowerOrder", b =>
                {
                    b.Property<int>("GrowerOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrowerOrderId"));

                    b.Property<decimal>("GreenTeaQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlaceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SuperTeaQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransportMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrowerOrderId");

                    b.ToTable("GrowerOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
