// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TfactoryMng.Data;

#nullable disable

namespace TfactoryMng.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250507060959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RtList", b =>
                {
                    b.Property<int>("rId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rId"));

                    b.Property<int?>("collectorId")
                        .HasColumnType("int");

                    b.Property<string>("distance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("endLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("rName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("startLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("vehicleId")
                        .HasColumnType("int");

                    b.HasKey("rId");

                    b.HasIndex("rName")
                        .IsUnique();

                    b.ToTable("RtLists");
                });

            modelBuilder.Entity("TfactoryMng.Model.GrowerLocation", b =>
                {
                    b.Property<int>("gId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gId"));

                    b.Property<int>("RtListId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.HasKey("gId");

                    b.HasIndex("RtListId");

                    b.ToTable("GrowerLocations");
                });

            modelBuilder.Entity("TfactoryMng.Model.GrowerLocation", b =>
                {
                    b.HasOne("RtList", "RtList")
                        .WithMany("GrowerLocations")
                        .HasForeignKey("RtListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RtList");
                });

            modelBuilder.Entity("RtList", b =>
                {
                    b.Navigation("GrowerLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
